// Sets tab: record a set, replay it live through the GUI, export it to audio.
#include <algorithm>
#include <cctype>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <filesystem>
#include <fstream>

#include "App.h"
#include "demo_set.h"  // generated by CMake from assets/sets/
#include "imgui.h"
#if defined(_WIN32)
#include "platform/win32_shell.h"
#endif

namespace fs = std::filesystem;
using ui::theme;

namespace {

const char* kDemoSetName = "Sunset to Jungle";

std::string safeFileName(const std::string& s) {
    std::string out;
    for (char c : s) out += (std::isalnum((unsigned char)c) || c == '-' || c == '_' || c == ' ') ? c : '_';
    while (!out.empty() && out.back() == ' ') out.pop_back();
    return out.empty() ? "set" : out;
}

std::string exportDir() {
#if defined(_WIN32)
    auto music = win32MusicFolders();
    if (!music.empty()) return (fs::u8path(music.front()) / "Afterglow").string();
    const char* home = std::getenv("USERPROFILE");
#else
    const char* home = std::getenv("HOME");
#endif
    return (fs::path(home ? home : ".") / "Music" / "Afterglow").string();
}

std::string trimmed(const std::string& s) {
    size_t a = s.find_first_not_of(' ');
    return a == std::string::npos ? "" : s.substr(a);
}

}  // namespace

void App::installDemoSet() {
    std::error_code ec;
    fs::create_directories(setsDir(), ec);
    const fs::path marker = fs::path(userDir) / ".demo_set_installed";
    if (fs::exists(marker, ec)) return;  // installed before (the user may have deleted it on purpose)
    std::ofstream(fs::path(setsDir()) / (std::string(kDemoSetName) + ".set"), std::ios::binary)
        .write(reinterpret_cast<const char*>(afterglow_demo_set), sizeof(afterglow_demo_set));
    std::ofstream(marker) << "1\n";
}

void App::refreshSets() {
    sets.clear();
    std::error_code ec;
    for (auto& it : fs::directory_iterator(setsDir(), ec)) {
        if (!it.is_regular_file() || it.path().extension() != ".set") continue;
        SetInfo info;
        info.path = it.path().string();
        info.name = it.path().stem().string();
        // Only the header is needed for the list.
        std::ifstream in(info.path);
        std::string line;
        for (int i = 0; i < 4 && std::getline(in, line); ++i) {
            if (line.rfind("length ", 0) == 0) info.lengthSec = std::atof(line.c_str() + 7) / kSampleRate;
        }
        sets.push_back(info);
    }
    std::sort(sets.begin(), sets.end(), [](const SetInfo& a, const SetInfo& b) { return a.name < b.name; });
    setsDirty = false;
}

void App::playSet(const std::string& path) { pendingReplayPath = path; }

void App::startPendingReplay() {
    if (pendingReplayPath.empty()) return;
    std::string path = pendingReplayPath;
    pendingReplayPath.clear();
    SetRecording set;
    std::string err;
    if (!loadSet(path, set, &err)) {
        toast("Can't play that set: " + err, theme.warn);
        return;
    }
    if (engine.isRecording()) {
        toast("Stop recording before playing a set", theme.warn);
        return;
    }
    autoDj = false;
    pendingLoad[0] = pendingLoad[1] = -1;
    replayName = set.name.empty() ? fs::path(path).stem().string() : set.name;
    engine.startReplay(std::move(set));
    toast("Playing set \"" + replayName + "\" - touch any control to take over", theme.good);
}

void App::stopAndSaveRecording() {
    if (!engine.isRecording()) return;
    std::string name = trimmed(recName);
    if (name.empty()) {
        char buf[64];
        std::time_t t = std::time(nullptr);
        std::strftime(buf, sizeof(buf), "My Set %Y-%m-%d %H.%M", std::localtime(&t));
        name = buf;
    }
    SetRecording set = engine.stopRecording(name);
    std::error_code ec;
    fs::create_directories(setsDir(), ec);
    fs::path file = fs::path(setsDir()) / (safeFileName(name) + ".set");
    for (int n = 2; fs::exists(file, ec); ++n) file = fs::path(setsDir()) / (safeFileName(name) + " " + std::to_string(n) + ".set");
    if (saveSet(file.string(), set)) toast("Saved set \"" + name + "\" (" + formatTime(set.lengthSec()) + ")", theme.good);
    else toast("Could not save the set to " + file.string(), theme.warn);
    recName[0] = 0;
    setsDirty = true;
}

void App::updateSets() {
    // Messages from the replay (runs on the audio thread).
    for (auto& n : engine.replayNotes) {
        std::string t = trimmed(n);
        if (!t.empty()) toast(t, IM_COL32(150, 200, 255, 255));
    }
    engine.replayNotes.clear();
    if (engine.tookOver) {
        engine.tookOver = false;
        toast("You took over the mix - set playback stopped", IM_COL32(255, 210, 60, 255));
    }
    if (engine.replayFinished) {
        engine.replayFinished = false;
        toast("Set \"" + replayName + "\" finished", theme.good);
    }

    // Prepare the audio for the next few loads before they fall due.
    if (engine.replayActive()) {
        int looked = 0;
        for (size_t i = engine.replayNext; i < engine.replay.events.size() && looked < 3; ++i) {
            SetEvent& ev = engine.replay.events[i];
            if (ev.action != SetAction::Load || ev.track.empty()) continue;
            ++looked;
            if (ev.resolved || ev.resolveFailed) continue;
            int idx = library.findByRef(ev.track);
            if (idx < 0) {
                ev.resolveFailed = true;
                toast("Set uses a track that isn't in your Library: " + ev.track.name, theme.warn);
                continue;
            }
            if (TrackPtr t = library.acquire(idx)) ev.resolved = t;
            else if (library.entry(idx)->state == EntryState::Failed) ev.resolveFailed = true;
        }
    }

    // Keep the Library highlight in sync with whatever is on the decks.
    for (int d = 0; d < 2; ++d) {
        const Track* t = engine.decks[d].track.get();
        if (t == lastDeckTrack[d]) continue;
        lastDeckTrack[d] = t;
        deckEntry[d] = library.findByTrack(t);
    }

    std::lock_guard<std::mutex> lock(exportMutex);
    if (!exportMessage.empty()) {
        toast(exportMessage, theme.good);
        exportMessage.clear();
    }
}

void App::exportSet(const SetInfo& info) {
    if (exportRunning) return;
    if (exportThread.joinable()) exportThread.join();
    SetRecording set;
    std::string err;
    if (!loadSet(info.path, set, &err)) {
        toast("Can't export: " + err, theme.warn);
        return;
    }
    std::error_code ec;
    fs::create_directories(exportDir(), ec);
    const std::string out = (fs::path(exportDir()) / (safeFileName(info.name) + ".wav")).string();
    exportName = info.name;
    exportRunning = true;
    exportProgress = 0.0f;
    exportThread = std::thread([this, set = std::move(set), out]() {
        // Resolve tracks through the Library (renders/decodes them if needed).
        auto resolve = [this](const TrackRef& ref) -> TrackPtr {
            int idx = library.findByRef(ref);
            if (idx < 0) return nullptr;
            for (;;) {
                if (TrackPtr t = library.acquire(idx)) return t;
                if (library.entry(idx)->state == EntryState::Failed) return nullptr;
                std::this_thread::sleep_for(std::chrono::milliseconds(30));
            }
        };
        std::string error;
        bool ok = renderSetToWav(set, resolve, out, &exportProgress, &error);
        std::lock_guard<std::mutex> lock(exportMutex);
        exportMessage = ok ? "Exported \"" + set.name + "\" to " + out : "Export failed: " + error;
        exportRunning = false;
    });
}

void App::drawSets() {
    if (setsDirty) refreshSets();

    // Recording controls.
    if (engine.isRecording()) {
        float blink = std::fmod(time, 1.0f) < 0.5f ? 1.0f : 0.35f;
        ImGui::TextColored(ImVec4(1, 0.25f, 0.25f, blink), "RECORDING");
        ImGui::SameLine();
        ImGui::Text("%s", formatTime(engine.recordingSec()).c_str());
        ImGui::SameLine();
        ImGui::SetNextItemWidth(220);
        ImGui::InputTextWithHint("##recname", "Name your set", recName, sizeof(recName));
        ImGui::SameLine();
        if (ui::ColoredButton("Stop & save", theme.good, ImVec2(0, 0), true)) stopAndSaveRecording();
        ImGui::SameLine();
        if (ImGui::Button("Discard")) {
            engine.stopRecording("");
            toast("Recording discarded");
        }
        ImGui::TextDisabled("Everything you do on the decks and mixer is being recorded, down to the sample.");
    } else {
        const bool canRecord = !engine.transitionBusy() && !engine.replayActive();
        ImGui::BeginDisabled(!canRecord);
        if (ui::ColoredButton("Record a set", IM_COL32(255, 70, 70, 255), ImVec2(130, 30), true)) {
            engine.startRecording();
            toast("Recording started - mix away!", IM_COL32(255, 120, 120, 255));
        }
        ImGui::EndDisabled();
        if (!canRecord) ui::Tip(engine.replayActive() ? "Stop the set that's playing first" : "Wait for the transition to finish");
        else ui::Tip("Records every move you make (loads, plays, knobs, transitions...) so the set can be replayed exactly");
        ImGui::SameLine();
        ImGui::TextWrapped("Record your mix, then replay it here: the decks, knobs and faders move on their own. "
                           "Touch any control during a replay to take over.");
    }

    // Replay status.
    if (engine.replayActive()) {
        ImGui::Separator();
        const double pos = double(engine.replayClock) / kSampleRate, len = engine.replay.lengthSec();
        ImGui::TextColored(ImVec4(0.5f, 0.85f, 1, 1), "PLAYING SET");
        ImGui::SameLine();
        ImGui::Text("%s", replayName.c_str());
        ImGui::SameLine();
        char ov[64];
        std::snprintf(ov, sizeof(ov), "%s / %s%s", formatTime(pos).c_str(), formatTime(len).c_str(),
                      engine.replayStalled ? "  (preparing a track...)" : "");
        ImGui::ProgressBar(len > 0 ? float(pos / len) : 0.0f, ImVec2(ImGui::GetContentRegionAvail().x - 70, 0), ov);
        ImGui::SameLine();
        if (ImGui::Button("Stop", ImVec2(60, 0))) {
            engine.stopReplay();
            for (int d = 0; d < 2; ++d) engine.pause(d);
        }
        ui::Tip("Stops the set and the music. (To keep the music going and take over, just touch a control.)");
    }
    if (exportRunning) {
        ImGui::Separator();
        ImGui::Text("Exporting \"%s\"...", exportName.c_str());
        ImGui::SameLine();
        ImGui::ProgressBar(exportProgress, ImVec2(-1, 0));
    }

    ImGui::Separator();
    if (sets.empty()) {
        ImGui::TextDisabled("No sets yet. Press \"Record a set\" and start mixing.");
        return;
    }
    if (!ImGui::BeginTable("##sets", 3, ImGuiTableFlags_RowBg | ImGuiTableFlags_ScrollY | ImGuiTableFlags_SizingStretchProp))
        return;
    ImGui::TableSetupScrollFreeze(0, 1);
    ImGui::TableSetupColumn("Set", 0, 3.0f);
    ImGui::TableSetupColumn("Length", ImGuiTableColumnFlags_WidthFixed, 70);
    ImGui::TableSetupColumn("", ImGuiTableColumnFlags_WidthFixed, 280);
    ImGui::TableHeadersRow();
    int toDelete = -1;
    for (int i = 0; i < int(sets.size()); ++i) {
        const SetInfo& s = sets[size_t(i)];
        ImGui::PushID(i);
        ImGui::TableNextRow();
        ImGui::TableSetColumnIndex(0);
        ImGui::AlignTextToFramePadding();
        ImGui::TextUnformatted(s.name.c_str());
        ImGui::TableSetColumnIndex(1);
        ImGui::TextUnformatted(formatTime(s.lengthSec).c_str());
        ImGui::TableSetColumnIndex(2);
        ImGui::BeginDisabled(engine.isRecording());
        if (ui::ColoredButton("Play live", theme.good, ImVec2(80, 0), true)) {
            if (liveDeck() >= 0 && !engine.replayActive()) ImGui::OpenPopup("##confirmplay");
            else playSet(s.path);
        }
        ImGui::EndDisabled();
        ui::Tip("Replays the set through the decks and mixer - watch it perform");
        if (ImGui::BeginPopup("##confirmplay")) {
            ImGui::Text("This stops the music that's playing now.");
            if (ui::ColoredButton("Play the set", theme.good, ImVec2(0, 0), true)) {
                playSet(s.path);
                ImGui::CloseCurrentPopup();
            }
            ImGui::SameLine();
            if (ImGui::Button("Cancel")) ImGui::CloseCurrentPopup();
            ImGui::EndPopup();
        }
        ImGui::SameLine();
        ImGui::BeginDisabled(exportRunning);
        if (ImGui::Button("Export audio")) exportSet(s);
        ImGui::EndDisabled();
        ui::Tip("Renders the set to a WAV file in your Music/Afterglow folder (runs in the background)");
        ImGui::SameLine();
        if (ImGui::Button("Delete")) ImGui::OpenPopup("##confirmdelete");
        if (ImGui::BeginPopup("##confirmdelete")) {
            ImGui::Text("Delete \"%s\"?", s.name.c_str());
            if (ui::ColoredButton("Delete", theme.warn, ImVec2(0, 0), true)) {
                toDelete = i;
                ImGui::CloseCurrentPopup();
            }
            ImGui::SameLine();
            if (ImGui::Button("Cancel")) ImGui::CloseCurrentPopup();
            ImGui::EndPopup();
        }
        ImGui::PopID();
    }
    ImGui::EndTable();
    if (toDelete >= 0) {
        std::error_code ec;
        fs::remove(sets[size_t(toDelete)].path, ec);
        setsDirty = true;
    }
}
